<?php
//Generated by CodeGenModel V2.0

namespace App\Models;
use CodeIgniter\Model;

class UserModel extends Model
{
    protected $table = 'user';
    protected $primaryKey = 'id_user';
	protected $useAutoIncrement = true;
    protected $returnType     = 'array';
    protected $useSoftDeletes = false;
    protected $allowedFields = [
        'id_user',
		'name',
		'firstname',
		'address',
		'city',
		'cp',
		'country',
		'rights',
		'mail',
		'password',
		'phone',
		'image_url',
		'newsletters',
		'current_job',
		'ratings',
		'gender',
		'birthday',
		'type',
		'status',
		'id_rdv',
		'id_tag',
    ];
}

